INSERT INTO station( gatunamn, stadsdel, stad) VALUES ("Svartgatan 19", "Västra Hisingen", "Göteborg");
INSERT INTO station( gatunamn, stadsdel, stad) VALUES ("Gröngatan 10", "Angered", "Göteborg");
INSERT INTO station( gatunamn, stadsdel, stad) VALUES ("Rosagatan 88", "Askim-Frölunda-Högsbo", "Göteborg");
INSERT INTO station( gatunamn, stadsdel, stad) VALUES ("Gulgatan 40", "Majorna-Linné", "Göteborg");
INSERT INTO station( gatunamn, stadsdel, stad) VALUES ("Blågatan 90", "Östra Göteborg", "Göteborg");

INSERT INTO fordon(klass) VALUES ("Personbil");
INSERT INTO fordon(klass) VALUES ("Taxi");
INSERT INTO fordon(klass) VALUES ("Buss");
INSERT INTO fordon(klass) VALUES ("Lätt Lastbil");
INSERT INTO fordon(klass) VALUES ("Tung Lastbil");

INSERT INTO transaktion(station_id, fordon_id, passage_id, tidpunkt_id, co2, pris) VALUES (1, 1, 1, 1, 180, 22);
INSERT INTO transaktion(station_id, fordon_id, passage_id, tidpunkt_id, co2, pris) VALUES (2, 1, 1, 1, 150, 16);
INSERT INTO transaktion(station_id, fordon_id, passage_id, tidpunkt_id, co2, pris) VALUES (1, 2, 1, 2, 180, 22);
INSERT INTO transaktion(station_id, fordon_id, passage_id, tidpunkt_id, co2, pris) VALUES (1, 2, 1, 1, 120, 22);
INSERT INTO transaktion(station_id, fordon_id, passage_id, tidpunkt_id, co2, pris) VALUES (1, 2, 1, 1, 120, 22);
INSERT INTO transaktion(station_id, fordon_id, passage_id, tidpunkt_id, co2, pris) VALUES (5, 5, 1, 2, 350, 9);

INSERT INTO tid(ar, manad, dag, timme, minut, sekund) VALUES(2015, 1, 30, 3, 20, 10);
INSERT INTO tid(ar, manad, dag, timme, minut, sekund) VALUES(2015, 2, 1, 14, 50, 55);

INSERT INTO passage(stadsdel,station_id) VALUES('Angered',1);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',2);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',3);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',4);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',5);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',6);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',7);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',8);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',9);
INSERT INTO passage(stadsdel,station_id) VALUES('Angered',10);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',1);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',2);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',3);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',4);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',5);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',6);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',7);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',8);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',9);
INSERT INTO passage(stadsdel,station_id) VALUES('Askim-Frölunda-Högsbo',10);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',1);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',2);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',3);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',4);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',5);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',6);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',7);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',8);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',9);
INSERT INTO passage(stadsdel,station_id) VALUES('Centrum',10);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',1);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',2);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',3);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',4);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',5);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',6);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',7);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',8);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',9);
INSERT INTO passage(stadsdel,station_id) VALUES('Lundby',10);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',1);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',2);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',3);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',4);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',5);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',6);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',7);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',8);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',9);
INSERT INTO passage(stadsdel,station_id) VALUES('Majorna-Linné',10);